title: Judul Situs
description: >-
  Write an awesome description for your new site here. 
facebook: adionakurniawan
twitter: adionakurniawan
youtube: https://www.youtube.com/channel/UCCM04WdV5sVd_Fhtf9IIZuw
email: adikurniawan1805@gmail.com

baseurl: ""
markdown: kramdown
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/:num/"
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      is_post: true
      permalink: /:title/