title: Judul Situs
description: >-
  Write an awesome description for your new site here. 
facebook: facebookusername
twitter: twitterusername
youtube: youtubelink
email: emailaddress

baseurl: ""
markdown: kramdown
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/:num/"
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      is_post: true
      permalink: /:title/